[package]
name = "tinic"
version = "0.1.0"
edition = "2024"


[dependencies]
retro_core.workspace = true
retro_controllers.workspace = true
retro_av.workspace = true
libretro_sys.workspace = true
generics.workspace = true
tokio.workspace = true
winit.workspace = true
