[package]
name = "tinic_super"
version = "0.1.0"
edition = "2024"

[dependencies]
generics.workspace = true
reqwest.workspace = true
zip.workspace = true
sevenz-rust.workspace = true
futures-util = "0.3.31"
tokio = { version = "1.49.0", features = ["full"] }